name: Bug report
description: Something isn’t working as expected
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps with which you can reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: Describe what you expected to happen
    validations:
      required: false
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: Describe what actually happened
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: Balatrolator URL
      description: If applicable, provide the share URL to your played hand
      placeholder: https://balatrolator.com/?state=---1-1--5-___________-11*_*_*_*_*_*_*_*_*_*_*_*-50*******_122*******_126*****0*3*_69****12.25***_132*******_119****5.5***-0*3***2**1_0*3**4*2**1_0*3**4*2**1_0*3**4*2**1_0*3**4*2**1_0*3**2***_0*3**5*2**_0*3**5*2**_0*3***2**
    validations:
      required: false
